{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2ff22e24_0c50fd72",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1329751
      },
      "writtenOn": "2022-10-19T21:05:48Z",
      "side": 1,
      "message": "PTAL, fixing my own bug here.",
      "revId": "1866246581755d320dffcef752e642aa90108246",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "b899b371_2396c29f",
        "filename": "src/tests/py_utils/android_helper.py",
        "patchSetId": 1
      },
      "lineNbr": 424,
      "author": {
        "id": 1531247
      },
      "writtenOn": "2022-10-19T21:17:54Z",
      "side": 1,
      "message": "This check is intentionally not conditional on `test_output_path` as we always want to check for failures regardless of whether output was requested or not\n\nWithout having a separate `ListTests` function like I did before, easiest is probably to check for `--list-tests` in args and special-case here, unless you have other ideas.",
      "range": {
        "startLine": 420,
        "startChar": 0,
        "endLine": 424,
        "endChar": 30
      },
      "revId": "1866246581755d320dffcef752e642aa90108246",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}