{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "9cddd64b_09aba236",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1326275
      },
      "writtenOn": "2021-02-26T16:25:04Z",
      "side": 1,
      "message": "I couldn\u0027t reproduce the failure locally",
      "revId": "d99cc1574b4ec9b35960bd627db8e54f82561d60",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}